from __future__ import annotations

from copy import deepcopy


def _capabilities(
    *,
    template_editor: bool = False,
    operations_preview: bool = False,
    preview_3d: bool = False,
    service_mapping: bool = False,
    estimate_export: bool = False,
    cutting_effect: bool = False,
) -> dict[str, bool]:
    return {
        "template_editor": template_editor,
        "operations_preview": operations_preview,
        "preview_3d": preview_3d,
        "service_mapping": service_mapping,
        "estimate_export": estimate_export,
        "cutting_effect": cutting_effect,
    }


PROCESSING_OPERATION_TYPE_REGISTRY: tuple[dict[str, object], ...] = (
    {
        "key": "hole",
        "name": "Отвір",
        "description": "Поточна присадка фурнітури для круглих отворів.",
        "category": "drilling",
        "status": "available",
        "geometry_kind": "cylinder",
        "required_fields": [
            "x_mm",
            "y_mm",
            "z_mm",
            "diameter_mm",
        ],
        "optional_fields": [
            "depth_mm",
            "is_through",
            "target_panel",
            "target_surface",
            "target_side",
            "side",
            "coordinate_system",
            "mounting_variant_key",
            "quantity",
            "mirrored",
            "order_index",
            "service_drilling_rule_id",
        ],
        "pricing_units": [
            "piece",
        ],
        "capabilities": _capabilities(
            template_editor=True,
            operations_preview=True,
            preview_3d=True,
            service_mapping=True,
        ),
        "version": 1,
    },
    {
        "key": "groove",
        "name": "Паз",
        "description": "Лінійний паз для майбутньої універсальної обробки.",
        "category": "routing",
        "status": "planned",
        "geometry_kind": "linear_slot",
        "required_fields": [
            "x_mm",
            "y_mm",
            "z_mm",
            "length_mm",
            "width_mm",
            "depth_mm",
        ],
        "optional_fields": [
            "direction",
            "end_radius_mm",
            "target_panel",
            "target_surface",
            "target_side",
            "quantity",
            "mirrored",
            "order_index",
        ],
        "pricing_units": [
            "piece",
            "linear_meter",
        ],
        "capabilities": _capabilities(
            operations_preview=True,
        ),
        "version": 1,
    },
    {
        "key": "quarter",
        "name": "Чверть",
        "description": "Крайова чверть для майбутніх операцій обробки.",
        "category": "routing",
        "status": "planned",
        "geometry_kind": "linear_slot",
        "required_fields": [
            "width_mm",
            "depth_mm",
            "edge",
        ],
        "optional_fields": [
            "start_offset_mm",
            "end_offset_mm",
            "quantity",
            "order_index",
        ],
        "pricing_units": [
            "linear_meter",
        ],
        "capabilities": _capabilities(
            operations_preview=True,
        ),
        "version": 1,
    },
    {
        "key": "pocket",
        "name": "Вибірка",
        "description": "Прямокутна вибірка для наступних етапів обробки.",
        "category": "routing",
        "status": "planned",
        "geometry_kind": "rectangular_pocket",
        "required_fields": [
            "x_mm",
            "y_mm",
            "width_mm",
            "height_mm",
            "depth_mm",
        ],
        "optional_fields": [
            "corner_radius_mm",
            "target_surface",
            "target_panel",
            "quantity",
            "order_index",
        ],
        "pricing_units": [
            "piece",
            "square_meter",
        ],
        "capabilities": _capabilities(),
        "version": 1,
    },
    {
        "key": "rectangular_cutout",
        "name": "Прямокутний виріз",
        "description": "Прямокутний виріз для майбутніх шаблонів.",
        "category": "contour",
        "status": "planned",
        "geometry_kind": "rectangular_cutout",
        "required_fields": [
            "x_mm",
            "y_mm",
            "width_mm",
            "height_mm",
        ],
        "optional_fields": [
            "corner_radius_mm",
            "is_through",
            "depth_mm",
            "target_surface",
            "target_panel",
            "quantity",
            "order_index",
        ],
        "pricing_units": [
            "piece",
            "contour_meter",
        ],
        "capabilities": _capabilities(),
        "version": 1,
    },
    {
        "key": "contour_cutout",
        "name": "Контурний виріз",
        "description": "Довільний контурний виріз для майбутніх шаблонів.",
        "category": "contour",
        "status": "planned",
        "geometry_kind": "contour",
        "required_fields": [
            "contour",
        ],
        "optional_fields": [
            "depth_mm",
            "is_through",
            "target_surface",
            "target_panel",
            "quantity",
            "order_index",
        ],
        "pricing_units": [
            "piece",
            "contour_meter",
        ],
        "capabilities": _capabilities(),
        "version": 1,
    },
    {
        "key": "radius",
        "name": "Радіус",
        "description": "Радіусні операції для майбутньої обробки крайок.",
        "category": "contour",
        "status": "planned",
        "geometry_kind": "corner_radius",
        "required_fields": [
            "radius_mm",
            "corner",
        ],
        "optional_fields": [
            "target_panel",
            "target_surface",
            "target_side",
            "quantity",
            "order_index",
        ],
        "pricing_units": [
            "piece",
        ],
        "capabilities": _capabilities(),
        "version": 1,
    },
    {
        "key": "milling",
        "name": "Фрезерування",
        "description": "Фрезерування та траєкторії для наступних етапів.",
        "category": "routing",
        "status": "planned",
        "geometry_kind": "toolpath",
        "required_fields": [
            "toolpath",
        ],
        "optional_fields": [
            "width_mm",
            "depth_mm",
            "passes",
            "target_surface",
            "target_panel",
            "quantity",
            "order_index",
        ],
        "pricing_units": [
            "linear_meter",
            "square_meter",
            "minute",
        ],
        "capabilities": _capabilities(),
        "version": 1,
    },
    {
        "key": "manual_operation",
        "name": "Ручна операція",
        "description": "Ручні роботи без автоматичної геометричної обробки.",
        "category": "manual",
        "status": "planned",
        "geometry_kind": "manual",
        "required_fields": [
            "name",
            "quantity",
        ],
        "optional_fields": [
            "description",
            "unit",
            "manual_price",
            "target_panel",
            "target_surface",
            "target_side",
            "order_index",
        ],
        "pricing_units": [
            "piece",
            "fixed",
            "minute",
        ],
        "capabilities": _capabilities(),
        "version": 1,
    },
)


def list_processing_operation_types() -> list[dict[str, object]]:
    return deepcopy(list(PROCESSING_OPERATION_TYPE_REGISTRY))
