import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

test("edge catalog navigation, filtering, and route restore wiring stay isolated from materials", () => {
  const appPath = new URL("../src/App.jsx", import.meta.url);
  const apiPath = new URL("../src/api.js", import.meta.url);
  const sidebarIconsPath = new URL("../src/sidebarIcons.js", import.meta.url);
  const source = readFileSync(appPath, "utf8");
  const apiSource = readFileSync(apiPath, "utf8");
  const sidebarIconsSource = readFileSync(sidebarIconsPath, "utf8");

  assert.match(source, /catalogEdges: "catalog-edges"/);
  assert.match(source, /if \(section === "catalog-edges"\) \{/);
  assert.match(source, /view: "catalogEdges"/);
  assert.match(source, /const \[edgeSearch, setEdgeSearch\] = useState\(\(\) => localStorage\.getItem\(EDGE_CATALOG_SEARCH_STORAGE_KEY\) \|\| ""\);/);
  assert.match(source, /const \[edgeManufacturerFilter, setEdgeManufacturerFilter\] = useState\(/);
  assert.match(source, /const \[edgeSupplierFilter, setEdgeSupplierFilter\] = useState\(/);
  assert.match(source, /const \[edgeCatalogViewMode, setEdgeCatalogViewMode\] = useState\(/);
  assert.match(source, /const \[edgeItems, setEdgeItems\] = useState\(\[\]\);/);
  assert.match(source, /const \[edgeCreateModalOpen, setEdgeCreateModalOpen\] = useState\(false\);/);
  assert.match(source, /const \[edgeCreateMode, setEdgeCreateMode\] = useState\("source"\);/);
  assert.match(source, /const \[edgeCreateForm, setEdgeCreateForm\] = useState\(\(\) => buildEdgeCreateForm\(\)\);/);
  assert.match(source, /const \[edgeCreateSourceUrl, setEdgeCreateSourceUrl\] = useState\(""\);/);
  assert.match(source, /const \[edgeCreateSourcePreview, setEdgeCreateSourcePreview\] = useState\(null\);/);
  assert.match(source, /const \[edgeCreateSourcePreviewLoading, setEdgeCreateSourcePreviewLoading\] = useState\(false\);/);
  assert.match(source, /const \[edgeCreateSourcePreviewError, setEdgeCreateSourcePreviewError\] = useState\(""\);/);
  assert.match(source, /loadEdgesCatalog\(token\);/);
  assert.match(source, /getEdgesCatalog\(/);
  assert.match(source, /createEdgeCatalog\(/);
  assert.match(source, /createEdgeCatalogFromSource\(/);
  assert.match(source, /previewEdgeCatalogSource\(/);
  assert.match(source, /uploadEdgeImage\(/);
  assert.match(source, /getEdgeCatalogDetail\(/);
  assert.match(source, /updateEdgeCatalog\(/);
  assert.match(source, /deleteEdgeCatalog\(/);
  assert.match(source, /const \[edgeCreateUploadedImageUrl, setEdgeCreateUploadedImageUrl\] = useState\(""\);/);
  assert.match(source, /const \[selectedEdgeDetail, setSelectedEdgeDetail\] = useState\(null\);/);
  assert.match(source, /const \[edgeDetailModalOpen, setEdgeDetailModalOpen\] = useState\(false\);/);
  assert.match(source, /isCatalogEdgesView \? \(/);
  assert.match(source, /fitting-category-breadcrumb fitting-category-breadcrumb-top/);
  assert.match(source, /Пошук крайок/);
  assert.match(source, /Виробник/);
  assert.match(source, /Постачальник/);
  assert.match(source, /All manufacturers/);
  assert.match(source, /All suppliers/);
  assert.match(source, /primary-button material-create-button/);
  assert.match(source, /Додати крайку/);
  assert.match(source, /edgeCreateModalOpen/);
  assert.match(source, /handleEdgeCreateSubmit/);
  assert.match(source, /handlePreviewEdgeCreateSource/);
  assert.match(source, /edgeCreateError/);
  assert.match(source, /edgeCreateCloseButtonRef/);
  assert.match(source, /edgeCreateMode === "source"/);
  assert.match(source, /edgeCreateMode === "manual"/);
  assert.match(source, /role="tablist" aria-label=\{language === "uk" \? "Спосіб створення" : "Create mode"\}/);
  assert.match(source, /За посиланням/);
  assert.match(source, /Вручну/);
  assert.match(source, /className=\{`primary-button\$\{edgeCreateMode === "source" && !edgeCreateSourcePreview \? " recommended-action" : ""\}`\}/);
  assert.match(source, /edgeCreateMode === "source" && !edgeCreateSourcePreview/);
  assert.match(source, /Завантажити дані/);
  assert.match(source, /Зображення крайки/);
  assert.match(source, /Завантажити файл/);
  assert.match(source, /URL зображення \(необов'язково\)|Image URL \(optional\)/);
  assert.match(source, /edgeCreateUploadedImageUrl \|\| edgeCreateForm\.image_url/);
  assert.match(source, /edgeCreate-preview-card|edge-create-preview-card/);
  assert.doesNotMatch(source, /Choose how to create an edge\./);
  assert.doesNotMatch(source, /Waiting for a link/);
  assert.doesNotMatch(source, /data-edge-action="confirm-source"/);
  assert.match(source, /edgeCatalogLoading && !edgeItems\.length/);
  assert.match(source, /edgeItems\.length \? /);
  assert.match(source, /Крайок поки немає\./);
  assert.match(source, /className=\{`icon-button\$\{edgeCatalogViewMode === "list" \? " active" : ""\}`\}/);
  assert.match(source, /className=\{`icon-button\$\{edgeCatalogViewMode === "grid" \? " active" : ""\}`\}/);
  assert.match(source, /material-card-clickable/);
  assert.match(source, /Детальна картка крайки|Edge details/);
  assert.match(source, /Редагувати крайку|Edit edge/);
  assert.match(source, /Видалити крайку|Delete edge/);
  assert.match(source, /material-edit-modal/);
  assert.match(source, /edge-details-modal/);
  assert.match(source, /edge-supplier-tabs/);
  assert.match(source, /edge-supplier-section/);
  assert.match(source, /edge-supplier-panel/);
  assert.match(source, /openMaterialEdgeDetails\(edgeItem\)/);
  assert.match(source, /edge-linked-materials-section/);
  assert.match(source, /edge-linked-materials-list/);
  assert.match(source, /setMaterialCategoryFilter\(""\);/);
  assert.match(source, /localStorage\.removeItem\(MATERIAL_CATEGORY_STORAGE_KEY\);/);
  assert.match(source, /const linkedCategoryCode = normalizeMaterialCategoryCode\(edgeItem\?\.material_category\);/);
  assert.match(source, /openMaterialCategoryCatalog\(linkedCategoryCode\)/);
  assert.match(source, /openMaterialCatalogRoot\(\)/);
  assert.match(source, /<MaterialImage[\s\S]*item=\{materialPreviewItem\}[\s\S]*token=\{token\}/);
  assert.match(source, /edge-linked-material-card-media/);
  assert.match(source, /edge-linked-material-card-actions/);
  assert.ok(source.indexOf('edge-linked-materials-section') < source.indexOf('<div className="fitting-details-content">'));
  assert.doesNotMatch(source, /edge-materials-section/);
  assert.doesNotMatch(source, /<article className="material-edge-card material-canonical-edge-card"[\s\S]{0,700}<div className="material-edge-card-topline">/);
  assert.doesNotMatch(source, /edge-supplier-detail-grid/);
  assert.doesNotMatch(source, /edge-supplier-price-grid/);
  assert.match(source, /sidebarFlyoutItems\.map\(\(item\) => \(/);
  assert.match(source, /key: "catalogEdges"/);
  assert.match(source, /label: language === "uk" \? "Крайки" : "Edges"/);
  assert.match(sidebarIconsSource, /catalogEdges: iconUrl\("materials\.png"\)/);
  assert.match(apiSource, /export async function getEdgesCatalog\(token, params = \{\}\)/);
  assert.match(apiSource, /export async function createEdgeCatalog\(token, payload\)/);
  assert.match(apiSource, /export async function previewEdgeCatalogSource\(token, payload\)/);
  assert.match(apiSource, /export async function createEdgeCatalogFromSource\(token, payload\)/);
  assert.match(apiSource, /return request\(`\/catalog\/edges/);

  assert.match(source, /const \[materialCategoryFilter, setMaterialCategoryFilter\] = useState\(\s*\(\) =>\s*initialAdminRoute\.view === "catalogMaterials"/);
  assert.match(source, /openMaterialCatalogRoot\(\)/);
  assert.match(source, /catalogMaterials: "catalog-materials"/);
  assert.match(source, /catalogMaterialsDescription/);
  assert.doesNotMatch(source, /isCatalogEdgesView \? \(\s*<section className="table-panel full-panel" key="catalogEdges">\s*<article className="catalog-card service-catalog-card service-catalog-card-full">\s*<div className="catalog-page-header">\s*<div className="service-catalog-title">\s*<h2>/);
});
