import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

test("supplier admin workspace keeps ownership fields and CRUD wiring explicit", () => {
  const appPath = fileURLToPath(new URL("../src/App.jsx", import.meta.url));
  const workspacePath = fileURLToPath(new URL("../src/components/FittingSuppliersAdminWorkspace.jsx", import.meta.url));
  const appSource = readFileSync(appPath, "utf8");
  const workspaceSource = readFileSync(workspacePath, "utf8");

  assert.match(appSource, /catalogSuppliers: "catalog-suppliers"/);
  assert.match(appSource, /const isCatalogSuppliersView = activeView === "catalogSuppliers";/);
  assert.match(appSource, /<FittingSuppliersAdminWorkspace[\s\S]*currentUserId=\{user\?\.id \|\| ""\}/);
  assert.match(appSource, /switchView\("catalogSuppliers"\)/);
  assert.match(appSource, /isMountingSchemesView \|\| isCatalogSuppliersView\s*\?\s*null/);
  assert.match(workspaceSource, /listFittingSuppliers/);
  assert.match(workspaceSource, /createFittingSupplier/);
  assert.match(workspaceSource, /updateFittingSupplier/);
  assert.match(workspaceSource, /deleteFittingSupplier/);
  assert.match(workspaceSource, /language === "uk" \? "Постачальники" : "Suppliers"/);
  assert.match(workspaceSource, /supplier-page-header/);
  assert.doesNotMatch(workspaceSource, /dashboard-hero-card/);
  assert.match(workspaceSource, /language === "uk" \? "Логотип" : "Logo"/);
  assert.match(workspaceSource, /type="file"/);
  assert.match(workspaceSource, /accept={SUPPLIER_LOGO_ACCEPT}/);
  assert.match(workspaceSource, /language === "uk" \? "Вибрати зображення" : "Choose image"/);
  assert.match(workspaceSource, /language === "uk" \? "Замінити" : "Replace"/);
  assert.match(workspaceSource, /language === "uk" \? "Видалити" : "Remove"/);
  assert.doesNotMatch(workspaceSource, /Пряме посилання на зображення/);
  assert.doesNotMatch(workspaceSource, /Direct image URL/);
  assert.match(workspaceSource, /SupplierLogo/);
  assert.match(workspaceSource, /logo_url/);
  assert.match(workspaceSource, /URL\.createObjectURL\(file\)/);
  assert.match(workspaceSource, /resolveAdminAssetUrl\(normalizedLogoUrl\)/);
  assert.match(workspaceSource, /supplier-logo-preview/);
  assert.match(workspaceSource, /supplier-form-body/);
  assert.match(workspaceSource, /supplier-form-options/);
  assert.match(workspaceSource, /supplier-form-footer/);
  assert.match(workspaceSource, /supplier-logo-file-input/);
  assert.match(workspaceSource, /supplier-logo-upload-panel/);
  assert.doesNotMatch(workspaceSource, /language === "uk" \? "Код" : "Code"/);
  assert.match(workspaceSource, /currentUserRole === "admin" \? \(/);
  assert.match(workspaceSource, /checked=\{Boolean\(editorForm\.is_system\)\}/);
  assert.match(workspaceSource, /checked=\{Boolean\(editorForm\.is_active\)\}/);
  assert.match(workspaceSource, /language === "uk" \? "Системний постачальник" : "System supplier"/);
  assert.match(workspaceSource, /language === "uk" \? "Активний" : "Active"/);
  assert.match(workspaceSource, /language === "uk" \? "Назва" : "Name"/);
  assert.match(workspaceSource, /supplier-logo-file-name/);
});
