import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

test("materials suppliers admin view reuses the supplier workspace with materials labels", () => {
  const appPath = fileURLToPath(new URL("../src/App.jsx", import.meta.url));
  const workspacePath = fileURLToPath(new URL("../src/components/FittingSuppliersAdminWorkspace.jsx", import.meta.url));
  const breadcrumbPath = fileURLToPath(new URL("../src/components/CatalogBreadcrumbTrail.jsx", import.meta.url));
  const appSource = readFileSync(appPath, "utf8");
  const workspaceSource = readFileSync(workspacePath, "utf8");
  const breadcrumbSource = readFileSync(breadcrumbPath, "utf8");
  const stylesSource = readFileSync(fileURLToPath(new URL("../src/styles.css", import.meta.url)), "utf8");

  assert.match(appSource, /catalogMaterialSuppliers: "catalog-material-suppliers"/);
  assert.match(appSource, /const isCatalogMaterialSuppliersView = activeView === "catalogMaterialSuppliers";/);
  assert.match(appSource, /const isMaterialCleanupView = isCatalogMaterialsView \|\| isMaterialTaxonomyManagementView \|\| isCatalogMaterialSuppliersView;/);
  assert.match(appSource, /switchView\("catalogMaterialSuppliers"\)/);
  assert.match(appSource, /Матеріали → Постачальники|Materials → Suppliers/);
  const liveSupplierRouteSource = appSource.slice(
    appSource.indexOf(") : isCatalogMaterialSuppliersView"),
    appSource.indexOf(") : isCatalogMaterialsView"),
  );
  assert.match(liveSupplierRouteSource, /<FittingSuppliersAdminWorkspace[\s\S]*breadcrumbCatalogLabel=\{language === "uk" \? "Довідники" : "Catalogs"\}/);
  assert.match(liveSupplierRouteSource, /breadcrumbRootLabel=\{language === "uk" \? "Матеріали" : "Materials"\}/);
  assert.match(liveSupplierRouteSource, /breadcrumbCurrentLabel=\{language === "uk" \? "Постачальники" : "Suppliers"\}/);
  assert.match(liveSupplierRouteSource, /onBreadcrumbCatalogClick=\{\(\) => switchView\("catalogHub"\)\}/);
  assert.match(liveSupplierRouteSource, /onBreadcrumbRootClick=\{\(\) => switchView\("catalogMaterials"\)\}/);
  assert.match(appSource, /<FittingSuppliersAdminWorkspace[\s\S]*description=\{language === "uk"[\s\S]*material suppliers/);
  assert.match(appSource, /user\.role === "admin"[\s\S]*catalogMaterialSuppliers/);
  assert.match(appSource, /nextView === "catalogMaterialSuppliers"/);
  assert.match(appSource, /key: "catalogMaterialSuppliers"/);
  assert.match(appSource, /label: language === "uk" \? "Матеріали → Постачальники" : "Materials → Suppliers"/);
  assert.match(appSource, /isMaterialCleanupView = isCatalogMaterialsView \|\| isMaterialTaxonomyManagementView \|\| isCatalogMaterialSuppliersView;/);
  assert.match(workspaceSource, /title = language === "uk" \? "Постачальники" : "Suppliers"/);
  assert.match(workspaceSource, /description = language === "uk"[\s\S]*fitting suppliers/);
  assert.match(workspaceSource, /breadcrumbRootLabel = ""/);
  assert.match(workspaceSource, /breadcrumbCurrentLabel = ""/);
  assert.match(workspaceSource, /onBreadcrumbRootClick = null/);
  assert.match(workspaceSource, /return \(\s*<section className="table-panel full-panel">/);
  assert.doesNotMatch(workspaceSource, /<section className="dashboard-layout">/);
  assert.match(workspaceSource, /catalog-page-header material-taxonomy-page-header supplier-page-header/);
  assert.match(workspaceSource, /service-catalog-header-actions material-taxonomy-page-actions supplier-page-actions/);
  assert.match(workspaceSource, /CatalogBreadcrumbTrail/);
  assert.match(workspaceSource, /breadcrumbCatalogLabel/);
  assert.match(workspaceSource, /onBreadcrumbCatalogClick/);
  assert.match(breadcrumbSource, /export default function CatalogBreadcrumbTrail/);
  assert.match(breadcrumbSource, /return \([\s\S]*<nav/);
  assert.match(breadcrumbSource, /item\.onClick/);
  assert.match(breadcrumbSource, /current: true|isCurrent/);
  assert.match(breadcrumbSource, /catalog-breadcrumb-link/);
  assert.match(breadcrumbSource, /aria-current=\{isCurrent \? "page" : undefined\}/);
  assert.match(workspaceSource, /<h1>\{title\}<\/h1>/);
  assert.match(workspaceSource, /<p>\{description\}<\/p>/);
  assert.match(workspaceSource, /listFittingSuppliers/);
  assert.match(workspaceSource, /fitting-manufacturer-logo[\s\S]*material-taxonomy-manufacturer-logo/);
  assert.match(workspaceSource, /manufacturer-logo-cell/);
  assert.match(workspaceSource, /material-taxonomy-manufacturer-scope-cell/);
  assert.match(workspaceSource, /materials-filter supplier-search/);
  assert.match(workspaceSource, /DeleteConfirmModal/);
  assert.match(workspaceSource, /openDeleteConfirm/);
  assert.match(workspaceSource, /performDelete/);
  assert.match(workspaceSource, /item\.is_active[\s\S]*Деактивувати[\s\S]*Активувати/);
  assert.match(workspaceSource, /<div className="catalog-actions">/);
  assert.match(workspaceSource, /className="icon-button"[\s\S]*onClick=\{\(\) => openEditor\(item\)\}[\s\S]*<Pencil size=\{14\} \/>/);
  assert.match(workspaceSource, /className="ghost-button compact-button"[\s\S]*onClick=\{\(\) => toggleActive\(item\)\}[\s\S]*Деактивувати[\s\S]*Активувати/);
  assert.match(workspaceSource, /className="ghost-button compact-button danger-button"[\s\S]*onClick=\{\(\) => openDeleteConfirm\(item\)\}[\s\S]*<Trash2 size=\{14\} \/>[\s\S]*Видалити/);
  assert.doesNotMatch(workspaceSource, /↘|↗/);
  assert.doesNotMatch(workspaceSource, /className="icon-button danger"[\s\S]*onClick=\{\(\) => openDeleteConfirm\(item\)\}/);
  assert.doesNotMatch(workspaceSource, /window\.confirm\(language === "uk" \? "Видалити постачальника\?"/);
  assert.doesNotMatch(workspaceSource, /supplier-toolbar-header/);
  assert.doesNotMatch(workspaceSource, /supplier-logo-mark/);
  assert.doesNotMatch(workspaceSource, /supplier-logo-cell/);
  assert.doesNotMatch(workspaceSource, /supplier-scope-cell/);
  assert.doesNotMatch(workspaceSource, /fitting-form-note/);
  assert.match(workspaceSource, /uploadSupplierLogo/);
  assert.match(workspaceSource, /SupplierLogo/);
  assert.match(stylesSource, /\.catalog-page-header\.supplier-page-header \.service-catalog-header-actions \{\s*align-items: center;/);
  assert.doesNotMatch(stylesSource, /\.catalog-page-header\.supplier-page-header \.service-catalog-header-actions \{\s*align-items: flex-start;/);
  assert.doesNotMatch(stylesSource, /\.suppliers-table \.catalog-actions \{\s*min-width: 0;/);
});
