import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

test("material detail renders supplier tabs above the detail layout and uses URL-only attach flow", () => {
  const appPath = fileURLToPath(new URL("../src/App.jsx", import.meta.url));
  const componentPath = fileURLToPath(new URL("../src/components/MaterialSupplierOffersSection.jsx", import.meta.url));
  const apiPath = fileURLToPath(new URL("../src/api.js", import.meta.url));
  const stylesPath = fileURLToPath(new URL("../src/styles.css", import.meta.url));
  const appSource = readFileSync(appPath, "utf8");
  const componentSource = readFileSync(componentPath, "utf8");
  const apiSource = readFileSync(apiPath, "utf8");
  const stylesSource = readFileSync(stylesPath, "utf8");

  const sectionIndex = appSource.indexOf("<MaterialSupplierOffersSection");
  const layoutIndex = appSource.indexOf('<div className="material-details-layout">');
  assert.ok(sectionIndex >= 0, "material supplier offers section should be rendered");
  assert.ok(layoutIndex >= 0, "material detail layout should be rendered");
  assert.ok(sectionIndex < layoutIndex, "supplier tabs should appear before the detail layout");
  assert.match(appSource, /className="confirm-modal material-details-modal material-details-scroll-modal"/);
  assert.match(appSource, /<div className="material-details-supplier-tabs">[\s\S]*<MaterialSupplierOffersSection/);
  assert.match(appSource, /<div className="material-details-layout">[\s\S]*className="material-details-media"[\s\S]*className="material-details-content"/);
  assert.match(appSource, /<MaterialSupplierOffersSection[\s\S]*materialDetail=\{selectedMaterialDetail\}/);
  assert.match(appSource, /<MaterialSupplierOffersSection[\s\S]*canEdit=\{canEditMaterialItem\(user, selectedMaterialDetail\)\}/);
  assert.match(appSource, /<MaterialSupplierOffersSection[\s\S]*onRefreshMaterialDetail=\{\(\) =>[\s\S]*openMaterialDetails\(selectedMaterialDetail, \{ keepVisible: true \}\)/);
  assert.match(appSource, /<MaterialSupplierOffersSection[\s\S]*onSelectedOfferActionsChange=\{setSelectedMaterialSupplierOfferActions\}/);
  assert.match(appSource, /<MaterialSupplierOffersSection[\s\S]*selectedOfferId=\{selectedMaterialSupplierOfferId\}/);
  assert.doesNotMatch(appSource, /selectedMaterialDetail\.display_article/);
  assert.doesNotMatch(appSource, /selectedMaterialDetail\.current_price/);
  assert.doesNotMatch(appSource, /renderSourceBadge\(getMaterialSourceMeta\(selectedMaterialDetail, t\)\)/);
  assert.match(appSource, /selectedMaterialSupplierOffer\?\.price/);
  assert.match(appSource, /selectedMaterialSupplierOffer\.article/);
  assert.match(appSource, /selectedMaterialSupplierOffer\.source_url/);
  assert.match(appSource, /materialDetailModalOpen && selectedMaterialDetail/);
  assert.match(appSource, /keepVisible: true/);
  assert.match(appSource, /status=\{materialSupplierOffersStatus\}/);
  assert.match(appSource, /materialSupplierOffersStatus/);
  assert.match(appSource, /function pickDefaultOfferId\(offers\)/);
  assert.match(appSource, /catch \(error\)/);
  assert.match(appSource, /setMaterialSupplierOffersStatus\("error"\)/);
  assert.match(appSource, /materialOwnersStatus/);
  assert.match(appSource, /formatCatalogCityLabel\(selectedMaterialSupplierOffer\.city, t\)/);
  assert.match(appSource, /selectedMaterialSupplierOffer\.region \?/);
  assert.doesNotMatch(appSource, /selectedMaterialSupplierOffer\.region \|\| t\.notSet/);
  assert.match(appSource, /selectedMaterialSupplierOffer\.supports_square_meter_sale/);
  assert.match(appSource, /import catalogSquareMeterImage from "\.\/assets\/catalog-hub\/catalog-square-meter\.png"/);
  assert.match(appSource, /shouldShowMaterialSquareMeterBadge\(item\)/);
  assert.match(appSource, /className="material-card-square-meter-badge"/);
  assert.match(appSource, /src=\{catalogSquareMeterImage\}/);
  assert.doesNotMatch(appSource, /className="material-card-square-meter-badge"[^>]*>[\s\S]*м²[\s\S]*<\/span>/);
  assert.match(appSource, /selectedMaterialSupplierOffer\?\.characteristics/);
  assert.match(appSource, /Характеристики/);
  assert.match(appSource, /Object\.entries\(characteristics\)/);
  assert.match(appSource, /materialCharacteristicsOpen/);
  assert.match(appSource, /aria-expanded=\{materialCharacteristicsOpen\}/);
  assert.match(appSource, /setMaterialCharacteristicsOpen\(\(open\) => !open\)/);
  assert.match(appSource, /fitting-details-section-card\$\{materialCharacteristicsOpen/);
  assert.match(appSource, /fitting-details-section-header fitting-details-section-toggle/);
  assert.match(appSource, /fitting-details-section-title/);
  assert.match(appSource, /fitting-details-characteristics-list/);
  assert.match(appSource, /fitting-details-characteristic/);
  assert.match(appSource, /<dt>\{name\}<\/dt>/);
  assert.match(appSource, /materialDescriptionOpen/);
  assert.match(appSource, /fitting-details-section-card\$\{materialDescriptionOpen/);
  assert.match(appSource, /fitting-details-description/);
  assert.match(appSource, /Чистий розмір \/ m²/);
  assert.match(appSource, /material-details-meta-row/);
  assert.match(appSource, /material-details-meta-actions/);
  assert.match(appSource, /material-details-supplier-card/);
  assert.match(appSource, /className="icon-button danger-button"/);
  assert.match(appSource, /selectedSupplierOfferActions\.onToggleActive/);
  assert.match(appSource, /selectedSupplierOfferActions\.onDelete/);
  assert.doesNotMatch(appSource, /material-details-supplier-meta/);

  assert.match(componentSource, /material-supplier-offers-topbar/);
  assert.match(componentSource, /material-supplier-offers-tabs/);
  assert.match(componentSource, /material-supplier-offer-tab-add/);
  assert.match(componentSource, /material-supplier-offer-tab-logo/);
  assert.match(componentSource, /aria-label=\{supplierName\}/);
  assert.match(componentSource, /supplierOffers = \[\]/);
  assert.match(componentSource, /const detailOffers = Array\.isArray\(supplierOffers\) && supplierOffers\.length/);
  assert.match(componentSource, /const normalizedStatus = hasVisibleOffers && shouldShowSupplierLoadingState\(status\) \? "loaded" : status;/);
  assert.match(componentSource, /showLoadingState/);
  assert.match(componentSource, /Loading supplier offers/);
  assert.doesNotMatch(componentSource, /material-supplier-offer-selected-toolbar/);
  assert.match(componentSource, /pickDefaultOfferId/);
  assert.match(componentSource, /sortSupplierOffers/);
  assert.match(componentSource, /attachMaterialSupplierOfferFromSource/);
  assert.match(componentSource, /Додати пропозицію/);
  assert.match(componentSource, /За посиланням/);
  assert.match(componentSource, /Вручну/);
  assert.match(componentSource, /Постачальник і дані товару будуть визначені автоматично\./);
  assert.match(componentSource, /Посилання на товар/);
  assert.match(componentSource, /DeleteConfirmModal/);
  assert.match(componentSource, /createMaterialSupplierOffer/);
  assert.match(componentSource, /updateMaterialSupplierOffer/);
  assert.match(componentSource, /deleteMaterialSupplierOffer/);
  assert.match(componentSource, /listFittingSuppliers/);
  assert.match(componentSource, /supplier_offers/);
  assert.match(componentSource, /material-supplier-offer-selected-supplier/);
  assert.doesNotMatch(componentSource, /material-supplier-offer-selected-actions/);
  assert.match(componentSource, /material-supplier-offer-form-note/);
  assert.match(componentSource, /type="url"/);

  const linkFlowStart = componentSource.indexOf('material-supplier-offer-link-flow');
  const manualFlowStart = componentSource.indexOf('<div className="hole-template-form-grid material-supplier-offer-form-grid">', linkFlowStart);
  assert.ok(linkFlowStart >= 0, "link flow block should exist");
  assert.ok(manualFlowStart > linkFlowStart, "manual flow should follow the link flow");
  const linkFlowSnippet = componentSource.slice(linkFlowStart, manualFlowStart);
  assert.match(linkFlowSnippet, /Supplier and product data will be detected automatically/);
  assert.match(linkFlowSnippet, /Source URL|Посилання на товар/);
  assert.match(linkFlowSnippet, /type="url"/);
  assert.doesNotMatch(linkFlowSnippet, /Supplier article|Артикул постачальника/);
  assert.doesNotMatch(linkFlowSnippet, /Price|Ціна/);
  assert.doesNotMatch(linkFlowSnippet, /Currency|Валюта/);
  assert.doesNotMatch(linkFlowSnippet, /Unit|Одиниця/);
  assert.doesNotMatch(linkFlowSnippet, /Availability|Наявність/);
  assert.doesNotMatch(linkFlowSnippet, /City|Місто/);
  assert.doesNotMatch(linkFlowSnippet, /Region|Регіон/);

  assert.doesNotMatch(componentSource, /fitting-details-section-card/);
  assert.doesNotMatch(componentSource, /fitting-details-section-header/);
  assert.doesNotMatch(componentSource, /ChevronRight/);
  assert.doesNotMatch(componentSource, /isOpen/);
  assert.doesNotMatch(componentSource, /window\.confirm/);
  assert.doesNotMatch(componentSource, /source_payload_json/);
  assert.doesNotMatch(componentSource, /parsed_at/);
  assert.doesNotMatch(componentSource, /price_updated_at/);
  assert.doesNotMatch(componentSource, /material-supplier-offer-selected-panel/);
  assert.doesNotMatch(componentSource, /material-supplier-offer-selected-grid/);
  assert.doesNotMatch(componentSource, /Save the supplier link now/);
  assert.doesNotMatch(componentSource, /Manual offers do not require a source URL/);

  assert.match(componentSource, /material-supplier-offers-empty-top/);
  assert.match(apiSource, /from-source/);
  assert.match(apiSource, /attachMaterialSupplierOfferFromSource/);
  assert.match(stylesSource, /material-supplier-offers-tabs/);
  assert.match(stylesSource, /material-supplier-offers-topbar/);
  assert.match(stylesSource, /material-supplier-offer-tab/);
  assert.doesNotMatch(stylesSource, /material-supplier-offer-selected-toolbar/);
  assert.match(stylesSource, /material-supplier-offer-selected-supplier/);
  assert.match(stylesSource, /material-details-meta-row/);
  assert.match(stylesSource, /material-details-supplier-card/);
  assert.match(stylesSource, /\.material-details-scroll-modal[\s\S]*display: flex;[\s\S]*flex-direction: column;[\s\S]*overflow: hidden/);
  assert.match(stylesSource, /\.material-details-scroll-modal > \.material-details-layout[\s\S]*min-height: 0;[\s\S]*overflow: hidden/);
  assert.match(stylesSource, /\.material-details-scroll-modal \.material-details-content[\s\S]*overflow-y: auto/);
  assert.match(stylesSource, /\.material-details-scroll-modal[\s\S]*display: block;[\s\S]*height: auto;[\s\S]*overflow: auto/);
  assert.match(stylesSource, /\.fitting-details-media[\s\S]*position: sticky;[\s\S]*top: 72px/);
  assert.match(stylesSource, /\.material-details-media[\s\S]*align-self: start;[\s\S]*height: fit-content;[\s\S]*position: sticky;[\s\S]*top: 72px/);
  assert.match(stylesSource, /\.material-details-media[\s\S]*position: static;[\s\S]*top: auto/);
  assert.match(stylesSource, /material-supplier-offer-form-note/);
});
