import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

test("materials home opens the category catalog and keeps breadcrumbs clickable", () => {
  const appPath = fileURLToPath(new URL("../src/App.jsx", import.meta.url));
  const stylesPath = fileURLToPath(new URL("../src/styles.css", import.meta.url));
  const source = readFileSync(appPath, "utf8");
  const stylesSource = readFileSync(stylesPath, "utf8");

  assert.match(source, /const MATERIAL_CATEGORY_STORAGE_KEY = "furniture_admin_material_category";/);
  assert.match(
    source,
    /const \[materialCategoryFilter, setMaterialCategoryFilter\] = useState\(\s*\(\) =>\s*initialAdminRoute\.view === "catalogMaterials"\s*\?\s*initialAdminRoute\.category \|\| ""\s*:\s*localStorage\.getItem\(MATERIAL_CATEGORY_STORAGE_KEY\) \|\| "",\s*\);/,
  );
  assert.match(source, /const isMaterialTaxonomyManagementView = isCatalogMaterialCategoriesView \|\| isCatalogMaterialManufacturersView;/);
  assert.match(source, /const isMaterialCleanupView = isCatalogMaterialsView \|\| isMaterialTaxonomyManagementView \|\| isCatalogMaterialSuppliersView;/);
  assert.match(source, /<section className=\{`workspace\$\{isMaterialCleanupView \? " materials-workspace" : ""\}`\}>/);
  assert.match(source, /const shouldHideFittingsCatalogOuterToolbar = isCatalogFittingsView \|\| isCatalogFastenersView;/);
  assert.match(source, /!isMaterialCleanupView && !isCatalogFittingManufacturersView && !shouldHideFittingsCatalogOuterToolbar && !isCatalogHubView \?/);
  assert.match(source, /\) : null\}\s*\n\s*\{isHomeView/);
  assert.match(source, /function openMaterialCatalogRoot\(\) \{[\s\S]*setMaterialCategoryFilter\(""\);[\s\S]*localStorage\.removeItem\(MATERIAL_CATEGORY_STORAGE_KEY\);[\s\S]*updateAdminHistory\(\{[\s\S]*category: null,[\s\S]*view: "catalogMaterials",[\s\S]*\}\);[\s\S]*\}/);
  assert.match(source, /function openMaterialCategoryCatalog\(categoryCode\) \{[\s\S]*setMaterialCategoryFilter\(normalizedCategoryCode\);[\s\S]*localStorage\.setItem\(MATERIAL_CATEGORY_STORAGE_KEY, normalizedCategoryCode\);[\s\S]*updateAdminHistory\(\{[\s\S]*category: normalizedCategoryCode,[\s\S]*view: "catalogMaterials",[\s\S]*\}\);[\s\S]*\}/);
  assert.match(source, /if \(nextView === "catalogMaterials"\) \{[\s\S]*openMaterialCatalogRoot\(\);[\s\S]*\}/);
  assert.match(source, /currentMaterialCategoryMeta/);
  assert.match(source, /useEffect\(\(\) => \{[\s\S]*localStorage\.setItem\(MATERIAL_CATEGORY_STORAGE_KEY, materialCategoryFilter\);[\s\S]*\}, \[materialCategoryFilter\]\);/);
  assert.match(source, /setMaterialCategoryFilter\(""\);/);
  assert.match(source, /replace: true/);
  assert.match(source, /materialCategoryCountByCode/);
  assert.match(source, /isMountingSchemesView \|\| isMaterialCleanupView \? null : activeView === "projectDetails"/);
  assert.match(source, /<div className="catalog-page-header material-taxonomy-page-header">/);
  assert.match(source, /fitting-category-breadcrumb fitting-category-breadcrumb-top/);
  assert.doesNotMatch(source, /material-category-detail-header/);
  assert.doesNotMatch(source, /<div className="service-catalog-header-actions catalog-page-header-actions">/);
  assert.match(source, /<article className="catalog-card service-catalog-card service-catalog-card-full">[\s\S]*<div className="catalog-page-header material-taxonomy-page-header">/);
  assert.match(source, /materials-root-panel/);
  assert.doesNotMatch(source, /material-category-detail-title/);
  assert.doesNotMatch(source, /material-category-detail-actions/);
  assert.match(source, /<div className="fitting-category-breadcrumb fitting-category-breadcrumb-top">[\s\S]*<button className="catalog-breadcrumb-link" onClick=\{\(\) => switchView\("catalogHub"\)\} type="button">[\s\S]*\{t\.catalog\}[\s\S]*<h3 className="catalog-breadcrumb-title">\{t\.catalogMaterials\}<\/h3>/);
  assert.match(source, /<div className="fitting-category-breadcrumb fitting-category-breadcrumb-top">[\s\S]*<button className="catalog-breadcrumb-link" onClick=\{\(\) => switchView\("catalogHub"\)\} type="button">[\s\S]*\{t\.catalog\}[\s\S]*<button className="catalog-breadcrumb-link" onClick=\{openMaterialCatalogRoot\} type="button">[\s\S]*\{t\.catalogMaterials\}[\s\S]*<h3 className="catalog-breadcrumb-title">\{currentMaterialCategoryMeta\?\.name \|\| formatCatalogLabel\(materialCategoryFilter, t\)\}<\/h3>/);
  assert.match(source, /<div className="service-catalog-header-actions">/);
  assert.match(source, /\{isCatalogMaterialRootView\s*\?/);
  assert.match(source, /materialsCatalogLoading && !materialCategories\.length/);
  assert.match(source, /materialsCatalogLoading && !materialItems\.length/);
  assert.match(source, /\$\{materialCategories\.length\} \$\{language === "uk" \? "категорій" : "categories"\}/);
  assert.match(source, /\$\{materialItems\.length\} \$\{t\.materialsCount\}/);
  assert.match(source, /<div className="fittings-toolbar-row material-category-toolbar-row">[\s\S]*<div className="fittings-toolbar-main">[\s\S]*<label className="service-catalog-search">/);
  assert.match(source, /<div className="fittings-toolbar-actions">[\s\S]*Додати матеріал/);
  assert.doesNotMatch(source, /<div className="materials-toolbar">[\s\S]*<label className="service-catalog-search">[\s\S]*<label className="materials-filter">/);
  assert.match(source, /className="fittings-view-toggle material-catalog-view-toggle"/);
  const listToggleIndex = source.indexOf('materialCatalogViewMode === "list" ? " active" : ""');
  const gridToggleIndex = source.indexOf('materialCatalogViewMode === "grid" ? " active" : ""');
  assert.ok(listToggleIndex > -1 && gridToggleIndex > -1 && listToggleIndex < gridToggleIndex);
  assert.match(source, /className=\{`icon-button\$\{materialCatalogViewMode === "list" \? " active" : ""\}`\}/);
  assert.match(source, /title=\{language === "uk" \? "Плитка" : "Grid"\}/);
  assert.match(source, /title=\{language === "uk" \? "Список" : "List"\}/);
  assert.doesNotMatch(source, /\{language === "uk" \? "Плитка" : "Tiles"\}/);
  assert.doesNotMatch(source, /\{language === "uk" \? "Список" : "List"\}<\/button>/);
  assert.match(source, /formatCatalogLabel\(activeCity, t\)/);
  assert.match(source, /materialsCatalogLoading && !materialItems\.length/);
  assert.match(source, /`\$\{materialItems\.length\} \$\{t\.materialsCount\}`/);
  assert.match(source, /listMaterialManufacturers\(/);
  assert.match(source, /const \[materialManufacturers, setMaterialManufacturers\] = useState\(\[\]\);/);
  assert.match(source, /materialManufacturersById/);
  assert.match(source, /getMaterialManufacturerMeta\(item, materialManufacturersById\)/);
  assert.match(source, /renderManufacturerBadge\(manufacturerMeta, \{ className: "fitting-manufacturer-badge" \}\)/);
  assert.match(source, /materialManufacturer: "Manufacturer"/);
  assert.match(source, /materialEditInvalidManufacturer/);
  assert.match(source, /newMaterialManufacturerId/);
  assert.match(source, /payload\.manufacturer_id = Number\(newMaterialManufacturerId\);/);
  assert.match(source, /<span>\{t\.materialManufacturer\}<\/span>/);
  assert.match(source, /<option value="">\{t\.notSet\}<\/option>/);
  assert.match(source, /materialCreateModalOpen/);
  assert.match(source, /closeMaterialCreateModal/);
  assert.match(source, /material-create-modal/);
  assert.match(source, /materials-quota-hint/);
  assert.doesNotMatch(source, /<article className="catalog-card service-catalog-card service-catalog-card-full">[\s\S]*material-category-detail-actions/);
  assert.match(source, /className="catalog-choice-card fitting-category-card material-category-card"[\s\S]*onClick=\{\(\) => openMaterialCategoryCatalog\(category\.code\)\}/);
  assert.match(source, /className="catalog-choice-media material-category-media"/);
  assert.match(source, /resolveAdminAssetUrl\(categoryImageUrl\)/);
  assert.match(source, /image_url/);
  assert.match(source, /Системні категорії|System categories/);
  assert.match(source, /Мої категорії|My categories/);
  assert.match(source, /material-category-preview-placeholder/);
  assert.match(source, /hasCategoryOwnershipMeta/);
  assert.match(source, /listMaterialCategories\(/);
  assert.match(source, /setMaterialCategories\(rootCategories\)/);
  assert.match(source, /material-category-groups/);
  assert.match(source, /material-category-group/);
  assert.match(source, /material-category-group-panel/);
  assert.match(source, /material-category-group-label/);
  assert.match(source, /categoryName = category\?\.name \|\| \(language === "uk" \? "Без назви" : "Untitled"\)/);
  assert.match(source, /const categoryDescription = String\(category\?\.description \|\| ""\)\.trim\(\)/);
  assert.match(source, /<span>\{categoryDescription\}<\/span>/);
  assert.match(source, /<span>\{t\.catalogMaterials\}<\/span>/);
  assert.doesNotMatch(source, /loadMaterialsCatalog\(token, \{ category: "" \}\)/);
  assert.match(source, /category: Object\.prototype\.hasOwnProperty\.call\(options, "category"\)/);
  assert.match(source, /isCatalogMaterialRootView \? \(/);
  assert.match(source, /<div className="fitting-category-breadcrumb fitting-category-breadcrumb-top">[\s\S]*<button className="catalog-breadcrumb-link" onClick=\{\(\) => switchView\("catalogHub"\)\} type="button">\s*\{t\.catalog\}\s*<\/button>[\s\S]*<span className="fitting-breadcrumb-separator">\/<\/span>[\s\S]*<h3 className="catalog-breadcrumb-title">\{t\.catalogMaterials\}<\/h3>/);
  assert.match(source, /Оберіть категорію, щоб відкрити матеріали всередині неї\./);
  assert.match(source, /<option key=\{category\.code\} value=\{category\.code\}>[\s\S]*category\?\.name \|\| formatCatalogLabel\(category\.code, t\)/);
  assert.match(source, /setMaterialCategoryFilter\(""\);[\s\S]*updateAdminHistory\(/);
  assert.match(source, /replace: true/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.table-panel\.full-panel \{\s*overflow: visible;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \{\s*[^}]*grid-template-rows: auto auto auto;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel\.materials-root-panel \{\s*display: block;[\s\S]*height: auto;[\s\S]*min-height: auto;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel\.materials-root-panel > \.catalog-card\.service-catalog-card\.service-catalog-card-full \{\s*min-height: auto;/);
  assert.match(stylesSource, /\.catalog-page-header\.material-taxonomy-page-header \{\s*display: flex;[\s\S]*margin: 0 0 16px;/);
  assert.match(stylesSource, /\.catalog-page-header\.material-taxonomy-page-header \.service-catalog-title \{\s*display: grid;[\s\S]*gap: 4px;/);
  assert.match(stylesSource, /\.catalog-page-header\.material-taxonomy-page-header \.service-catalog-header-actions \{\s*align-items: center;[\s\S]*max-width: min\(100%, 760px\);/);
  assert.match(stylesSource, /\.fittings-toolbar-row \{\s*align-items: flex-end;[\s\S]*margin: 4px 0 12px;/);
  assert.doesNotMatch(stylesSource, /\.materials-toolbar-inline \{/);
  assert.doesNotMatch(stylesSource, /\.material-category-breadcrumb \{/);
  assert.doesNotMatch(stylesSource, /\.material-category-detail-title \.fitting-breadcrumb-link,[\s\S]*font-size: 14px;/);
  assert.doesNotMatch(stylesSource, /\.material-category-detail-title \.fitting-breadcrumb-separator[\s\S]*font-size: 14px;/);
  assert.match(stylesSource, /\.fitting-breadcrumb-link \{\s*background: transparent;[\s\S]*font-size: 18px;/);
  assert.match(stylesSource, /\.catalog-breadcrumb-title \{\s*align-items: center;[\s\S]*font-size: 25px;[\s\S]*font-weight: 800;[\s\S]*line-height: 1\.25;/);
  assert.match(stylesSource, /\.catalog-breadcrumb-link \{\s*background: transparent;[\s\S]*font-size: inherit;[\s\S]*font-weight: 800;[\s\S]*line-height: inherit;/);
  assert.match(stylesSource, /\.material-create-button \{\s*white-space: nowrap;/);
  assert.match(stylesSource, /\.material-create-modal \{\s*display: flex;[\s\S]*max-width: 760px;[\s\S]*width: min\(100%, 760px\);/);
  assert.match(stylesSource, /Materials workspace standard: content panels grow with content; do not reintroduce fixed viewport-height or nested scroll on taxonomy\/list screens\./);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel \{\s*display: block;[\s\S]*flex: none;[\s\S]*height: auto;[\s\S]*min-height: auto;/);
  assert.doesNotMatch(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel \{\s*display: flex;[\s\S]*min-height: 0;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel > \.catalog-card\.service-catalog-card\.service-catalog-card-full \{\s*min-height: auto;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.catalog-category-groups \{\s*display: grid;[\s\S]*gap: 18px;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.catalog-category-group \{\s*display: grid;[\s\S]*gap: 10px;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.material-category-group-panel \{\s*background:[\s\S]*border-radius: 14px;[\s\S]*padding: 14px;/);
});
