import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

test("material taxonomy admin views are wired into the catalog sidebar and render tree", () => {
  const appPath = fileURLToPath(new URL("../src/App.jsx", import.meta.url));
  const stylesPath = fileURLToPath(new URL("../src/styles.css", import.meta.url));
  const workspacePath = fileURLToPath(new URL("../src/components/MaterialTaxonomyAdminWorkspace.jsx", import.meta.url));
  const appSource = readFileSync(appPath, "utf8");
  const stylesSource = readFileSync(stylesPath, "utf8");
  const workspaceSource = readFileSync(workspacePath, "utf8");

  assert.match(appSource, /catalogMaterialCategories: "catalog-material-categories"/);
  assert.match(appSource, /catalogMaterialManufacturers: "catalog-material-manufacturers"/);
  assert.match(appSource, /catalogMaterialCategories/);
  assert.match(appSource, /catalogMaterialManufacturers/);
  assert.match(appSource, /switchView\("catalogMaterialCategories"\)/);
  assert.match(appSource, /switchView\("catalogMaterialManufacturers"\)/);
  assert.match(appSource, /<MaterialTaxonomyAdminWorkspace[\s\S]*entity="categories"/);
  assert.match(appSource, /<MaterialTaxonomyAdminWorkspace[\s\S]*entity="manufacturers"/);
  assert.match(appSource, /canViewMaterialCatalog[\s\S]*catalogMaterialCategories/);
  assert.match(appSource, /user\.role === "admin"[\s\S]*catalogMaterialManufacturers/);
  assert.match(appSource, /currentUser=\{user\}[\s\S]*canCreate=\{canCreateMaterialCatalog\}/);
  assert.match(appSource, /<MaterialTaxonomyAdminWorkspace[\s\S]*entity="manufacturers"[\s\S]*canCreate=\{canCreateMaterialCatalog\}/);
  assert.match(workspaceSource, /listMaterialCategories/);
  assert.match(workspaceSource, /listMaterialManufacturers/);
  assert.match(workspaceSource, /createMaterialCategory/);
  assert.match(workspaceSource, /updateMaterialCategory/);
  assert.match(workspaceSource, /deleteMaterialCategory/);
  assert.match(workspaceSource, /uploadMaterialCategoryImage/);
  assert.match(workspaceSource, /uploadMaterialManufacturerLogo/);
  assert.match(workspaceSource, /resolveAdminAssetUrl/);
  assert.match(workspaceSource, /MaterialCategoryThumbnail/);
  assert.match(workspaceSource, /MaterialLogoPreview/);
  assert.match(workspaceSource, /MaterialManufacturerLogo/);
  assert.match(workspaceSource, /createMaterialManufacturer/);
  assert.match(workspaceSource, /updateMaterialManufacturer/);
  assert.match(workspaceSource, /deleteMaterialManufacturer/);
  assert.match(workspaceSource, /DeleteConfirmModal/);
  assert.match(workspaceSource, /toggleActive/);
  assert.match(workspaceSource, /showInactive/);
  assert.match(workspaceSource, /categoryScope/);
  assert.match(workspaceSource, /Системні|System/);
  assert.match(workspaceSource, /Користувацькі|User-owned/);
  assert.match(workspaceSource, /Всі|All/);
  assert.match(workspaceSource, /Власник|Owner/);
  assert.match(workspaceSource, /getCategoryOwnerDisplayLabel/);
  assert.match(workspaceSource, /owner_display_name/);
  assert.match(workspaceSource, /owner_login/);
  assert.match(workspaceSource, /owner_email/);
  assert.match(workspaceSource, /website/i);
  assert.match(workspaceSource, /is_active/);
  assert.match(workspaceSource, /fittings-table-header/);
  assert.match(workspaceSource, /fittings-table-row/);
  assert.match(workspaceSource, /material-taxonomy-page-header/);
  assert.match(workspaceSource, /material-taxonomy-page-actions/);
  assert.match(workspaceSource, /<button className="primary-button" onClick=\{\(\) => openEditor\(\)\} type="button">[\s\S]*Додати[\s\S]*<\/button>/);
  assert.match(workspaceSource, /confirm-modal supplier-confirm-modal/);
  assert.match(workspaceSource, /breadcrumb:\s*\{\s*uk:\s*"Категорії"/);
  assert.doesNotMatch(workspaceSource, /<h3>\{config\.title\[language\] \|\| config\.title\.uk\}<\/h3>/);
  assert.match(workspaceSource, /breadcrumb:\s*\{\s*uk:\s*"Виробники"/);
  assert.match(workspaceSource, /material-taxonomy-page-title/);
  assert.doesNotMatch(workspaceSource, /<h3>\{config\.title\[language\] \|\| config\.title\.uk\}<\/h3>/);
  assert.match(workspaceSource, /description:\s*String\(item\?\.description \|\| ""\)/);
  assert.match(workspaceSource, /image_url:\s*String\(item\?\.image_url \|\| ""\)/);
  assert.match(workspaceSource, /Опис|Description/);
  assert.match(workspaceSource, /Image URL/);
  assert.match(workspaceSource, /Завантажити файл|Upload file/);
  assert.match(workspaceSource, /URL зображення|Image URL/);
  assert.match(workspaceSource, /accept={MATERIAL_CATEGORY_IMAGE_ACCEPT}/);
  assert.match(workspaceSource, /accept={MATERIAL_MANUFACTURER_LOGO_ACCEPT}/);
  assert.match(workspaceSource, /supplier-logo-file-input/);
  assert.match(workspaceSource, /material-taxonomy-table/);
  assert.match(workspaceSource, /material-taxonomy-thumbnail/);
  assert.match(workspaceSource, /material-taxonomy-thumbnail-placeholder/);
  assert.match(workspaceSource, /material-taxonomy-table--manufacturers/);
  assert.match(workspaceSource, /manufacturer-logo-cell/);
  assert.match(workspaceSource, /material-taxonomy-manufacturer-scope-cell/);
  assert.match(workspaceSource, /supplier-logo-preview--contain/);
  assert.match(workspaceSource, /Зображення/);
  assert.match(workspaceSource, /getCategoryOwnershipLabel/);
  assert.match(workspaceSource, /getCategoryActiveLabel/);
  assert.match(workspaceSource, /getManufacturerOwnershipLabel/);
  assert.match(workspaceSource, /getManufacturerOwnerDisplayLabel/);
  assert.match(workspaceSource, /canDeleteManufacturerRow/);
  assert.match(workspaceSource, /handleDeleteCategory/);
  assert.match(workspaceSource, /openDeleteManufacturerConfirm/);
  assert.match(workspaceSource, /performDeleteManufacturer/);
  assert.match(workspaceSource, /danger-button/);
  assert.match(workspaceSource, /<button className="ghost-button compact-button danger-button" onClick=\{\(\) => openDeleteManufacturerConfirm\(item\)\} type="button">[\s\S]*Видалити[\s\S]*<\/button>/);
  assert.doesNotMatch(workspaceSource, /handleDeleteManufacturer[\s\S]*window\.confirm/);
  assert.match(workspaceSource, /<div className="catalog-page-header material-taxonomy-page-header">/);
  assert.match(workspaceSource, /<div className="service-catalog-header-actions material-taxonomy-page-actions">/);
  assert.match(workspaceSource, /<article className="catalog-card service-catalog-card service-catalog-card-full">/);
  assert.doesNotMatch(workspaceSource, /config\.columns\.code/);
  assert.doesNotMatch(workspaceSource, /editorForm\.code/);
  assert.doesNotMatch(workspaceSource, /<div className="service-catalog-header-actions">[\s\S]*<div className="table-panel full-panel">/);
  assert.match(workspaceSource, /config\.title\[language\] \|\| config\.title\.uk/);
  assert.match(workspaceSource, /config\.breadcrumb\[language\] \|\| config\.breadcrumb\.uk/);
  assert.doesNotMatch(workspaceSource, /Parent category/i);
  assert.doesNotMatch(workspaceSource, /setEditorParentId/);
  assert.match(stylesSource, /material-taxonomy-table--admin/);
  assert.match(stylesSource, /material-taxonomy-table--user/);
  assert.match(stylesSource, /minmax\(180px, 1\.2fr\)/);
  assert.match(stylesSource, /minmax\(180px, 1\.35fr\)/);
  assert.match(stylesSource, /\.material-taxonomy-table \.catalog-actions \{[\s\S]*gap: 8px;[\s\S]*min-width: 0;/);
  assert.match(stylesSource, /\.supplier-logo-preview--contain \{\s*justify-content: center;/);
  assert.match(stylesSource, /\.supplier-logo-preview-mark \{[\s\S]*object-fit: contain;/);
  assert.match(stylesSource, /\.material-taxonomy-table--manufacturers \.manufacturer-logo-cell \{[\s\S]*display: flex;/);
  assert.match(stylesSource, /\.material-taxonomy-table--manufacturers \.manufacturer-logo-cell \{[\s\S]*justify-content: center;/);
  assert.match(stylesSource, /\.material-taxonomy-manufacturer-logo \{[\s\S]*max-width: 100%;/);
  assert.match(stylesSource, /Materials taxonomy header standard: title block and actions are vertically centered on desktop\./);
  assert.match(stylesSource, /\.material-taxonomy-page-header \{\s*align-items: center;/);
  assert.match(stylesSource, /\.material-taxonomy-page-actions \{\s*align-items: center;[\s\S]*flex-wrap: nowrap;/);
  assert.match(stylesSource, /@media \(max-width: 1200px\) \{\s*\.material-taxonomy-page-actions \{\s*flex-wrap: wrap;/);
});
