import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

test("materials home opens the category catalog and keeps breadcrumbs clickable", () => {
  const appPath = fileURLToPath(new URL("../src/App.jsx", import.meta.url));
  const stylesPath = fileURLToPath(new URL("../src/styles.css", import.meta.url));
  const source = readFileSync(appPath, "utf8");
  const stylesSource = readFileSync(stylesPath, "utf8");

  assert.match(source, /const MATERIAL_CATEGORY_STORAGE_KEY = "furniture_admin_material_category";/);
  assert.match(source, /const \[materialCategoryFilter, setMaterialCategoryFilter\] = useState\(\s*\(\) => localStorage\.getItem\(MATERIAL_CATEGORY_STORAGE_KEY\) \|\| "",\s*\);/);
  assert.match(source, /const isMaterialTaxonomyManagementView = isCatalogMaterialCategoriesView \|\| isCatalogMaterialManufacturersView;/);
  assert.match(source, /const isMaterialCleanupView = isCatalogMaterialsView \|\| isMaterialTaxonomyManagementView \|\| isCatalogMaterialSuppliersView;/);
  assert.match(source, /<section className=\{`workspace\$\{isMaterialCleanupView \? " materials-workspace" : ""\}`\}>/);
  assert.match(source, /!isMaterialCleanupView && !isCatalogFittingManufacturersView \? \(/);
  assert.match(source, /\) : null\}\s*\n\s*\{isHomeView/);
  assert.match(source, /function openMaterialCatalogRoot\(\) \{[\s\S]*setMaterialCategoryFilter\(""\);[\s\S]*localStorage\.removeItem\(MATERIAL_CATEGORY_STORAGE_KEY\);[\s\S]*\}/);
  assert.match(source, /function openMaterialCategoryCatalog\(categoryCode\) \{[\s\S]*setMaterialCategoryFilter\(normalizedCategoryCode\);[\s\S]*localStorage\.setItem\(MATERIAL_CATEGORY_STORAGE_KEY, normalizedCategoryCode\);[\s\S]*\}/);
  assert.match(source, /if \(nextView === "catalogMaterials"\) \{[\s\S]*openMaterialCatalogRoot\(\);[\s\S]*\}/);
  assert.match(source, /currentMaterialCategoryMeta/);
  assert.match(source, /useEffect\(\(\) => \{[\s\S]*localStorage\.setItem\(MATERIAL_CATEGORY_STORAGE_KEY, materialCategoryFilter\);[\s\S]*\}, \[materialCategoryFilter\]\);/);
  assert.match(source, /materialCategoryCountByCode/);
  assert.match(source, /isMountingSchemesView \|\| isMaterialCleanupView \? null : activeView === "projectDetails"/);
  assert.match(source, /fitting-category-breadcrumb fitting-category-breadcrumb-top/);
  assert.match(source, /material-category-detail-header/);
  assert.match(source, /<div className="service-catalog-header-actions catalog-page-header-actions">/);
  assert.match(source, /<div className="catalog-page-header">[\s\S]*<article className="catalog-card service-catalog-card service-catalog-card-full">/);
  assert.match(source, /materials-root-panel/);
  assert.match(source, /material-category-detail-title/);
  assert.match(source, /material-category-detail-actions/);
  assert.doesNotMatch(source, /<div className="service-catalog-title material-category-detail-title">[\s\S]*<h3>\{currentMaterialCategoryMeta\?\.name \|\| formatCatalogLabel\(materialCategoryFilter, t\)\}<\/h3>/);
  assert.match(source, /<div className="service-catalog-header-actions material-category-detail-actions">/);
  assert.match(source, /<div className="service-catalog-header-actions material-category-detail-actions">[\s\S]*<div className="materials-toolbar materials-toolbar-inline">[\s\S]*<label className="service-catalog-search">/);
  assert.doesNotMatch(source, /<div className="materials-toolbar">[\s\S]*<label className="service-catalog-search">[\s\S]*<label className="materials-filter">/);
  assert.match(source, /formatCatalogLabel\(activeCity, t\)/);
  assert.match(source, /materialsCatalogLoading && !materialItems\.length/);
  assert.match(source, /`\$\{materialItems\.length\} \$\{t\.materialsCount\}`/);
  assert.match(source, /listMaterialManufacturers\(/);
  assert.match(source, /const \[materialManufacturers, setMaterialManufacturers\] = useState\(\[\]\);/);
  assert.match(source, /materialManufacturersById/);
  assert.match(source, /getMaterialManufacturerMeta\(item, materialManufacturersById\)/);
  assert.match(source, /renderManufacturerBadge\(manufacturerMeta, \{ className: "fitting-manufacturer-badge" \}\)/);
  assert.match(source, /materialManufacturer: "Manufacturer"/);
  assert.match(source, /materialEditInvalidManufacturer/);
  assert.match(source, /newMaterialManufacturerId/);
  assert.match(source, /payload\.manufacturer_id = Number\(newMaterialManufacturerId\);/);
  assert.match(source, /<span>\{t\.materialManufacturer\}<\/span>/);
  assert.match(source, /<option value="">\{t\.notSet\}<\/option>/);
  assert.doesNotMatch(source, /<article className="catalog-card service-catalog-card service-catalog-card-full">[\s\S]*material-category-detail-actions/);
  assert.match(source, /className="catalog-choice-card fitting-category-card material-category-card"[\s\S]*onClick=\{\(\) => openMaterialCategoryCatalog\(category\.code\)\}/);
  assert.match(source, /className="catalog-choice-media material-category-media"/);
  assert.match(source, /resolveAdminAssetUrl\(categoryImageUrl\)/);
  assert.match(source, /image_url/);
  assert.match(source, /Системні категорії|System categories/);
  assert.match(source, /Мої категорії|My categories/);
  assert.match(source, /material-category-preview-placeholder/);
  assert.match(source, /hasCategoryOwnershipMeta/);
  assert.match(source, /listMaterialCategories\(/);
  assert.match(source, /setMaterialCategories\(rootCategories\)/);
  assert.match(source, /material-category-groups/);
  assert.match(source, /material-category-group/);
  assert.match(source, /material-category-group-panel/);
  assert.match(source, /material-category-group-label/);
  assert.match(source, /categoryName = category\?\.name \|\| \(language === "uk" \? "Без назви" : "Untitled"\)/);
  assert.match(source, /const categoryDescription = String\(category\?\.description \|\| ""\)\.trim\(\)/);
  assert.match(source, /<span>\{categoryDescription\}<\/span>/);
  assert.match(source, /<span>\{t\.catalogMaterials\}<\/span>/);
  assert.doesNotMatch(source, /loadMaterialsCatalog\(token, \{ category: "" \}\)/);
  assert.match(source, /category: Object\.prototype\.hasOwnProperty\.call\(options, "category"\)/);
  assert.match(source, /isCatalogMaterialRootView \? \(/);
  assert.match(source, /<h3>\{language === "uk" \? "Матеріали" : "Materials"\}<\/h3>/);
  assert.match(source, /Оберіть категорію, щоб відкрити матеріали всередині неї\./);
  assert.match(source, /<option key=\{category\.code\} value=\{category\.code\}>[\s\S]*category\?\.name \|\| formatCatalogLabel\(category\.code, t\)/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.table-panel\.full-panel \{\s*overflow: visible;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \{\s*[^}]*grid-template-rows: auto auto auto;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel\.materials-root-panel \{\s*display: block;[\s\S]*height: auto;[\s\S]*min-height: auto;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel\.materials-root-panel > \.catalog-card\.service-catalog-card\.service-catalog-card-full \{\s*min-height: auto;/);
  assert.match(stylesSource, /\.materials-toolbar-inline \{\s*align-items: center;[\s\S]*justify-content: flex-end;[\s\S]*min-width: 0;/);
  assert.match(stylesSource, /Materials workspace standard: content panels grow with content; do not reintroduce fixed viewport-height or nested scroll on taxonomy\/list screens\./);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel \{\s*display: block;[\s\S]*flex: none;[\s\S]*height: auto;[\s\S]*min-height: auto;/);
  assert.doesNotMatch(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel \{\s*display: flex;[\s\S]*min-height: 0;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace > \.table-panel\.full-panel > \.catalog-card\.service-catalog-card\.service-catalog-card-full \{\s*min-height: auto;/);
  assert.match(stylesSource, /\.material-category-detail-header \{\s*align-items: center;/);
  assert.match(stylesSource, /\.material-category-detail-actions \{\s*margin-left: auto;[\s\S]*align-self: center;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.catalog-category-groups \{\s*display: grid;[\s\S]*gap: 18px;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.catalog-category-group \{\s*display: grid;[\s\S]*gap: 10px;/);
  assert.match(stylesSource, /\.workspace\.materials-workspace \.material-category-group-panel \{\s*background:[\s\S]*border-radius: 14px;[\s\S]*padding: 14px;/);
});
