import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

test("collapsed sidebar hover flyout wiring keeps hover separate from click navigation", () => {
  const appPath = fileURLToPath(new URL("../src/App.jsx", import.meta.url));
  const stylesPath = fileURLToPath(new URL("../src/styles.css", import.meta.url));
  const appSource = readFileSync(appPath, "utf8");
  const stylesSource = readFileSync(stylesPath, "utf8");

  assert.match(appSource, /onPointerEnter=\{\(event\) => openSidebarFlyoutOnHover\("processing", event\)\}/);
  assert.match(appSource, /onPointerEnter=\{\(event\) => openSidebarFlyoutOnHover\("connections", event\)\}/);
  assert.match(appSource, /onPointerEnter=\{\(event\) => openSidebarFlyoutOnHover\("catalog", event\)\}/);
  assert.match(appSource, /onPointerLeave=\{scheduleSidebarFlyoutClose\}/);
  assert.match(appSource, /const \[sidebarCatalogSubmenuKey, setSidebarCatalogSubmenuKey\] = useState\(""\);/);
  assert.match(appSource, /const \[sidebarCatalogMaterialsCategorySubmenuOpen, setSidebarCatalogMaterialsCategorySubmenuOpen\] = useState\(false\);/);
  assert.match(appSource, /const \[sidebarCatalogFittingCategoriesSubmenuOpen, setSidebarCatalogFittingCategoriesSubmenuOpen\] = useState\(false\);/);
  assert.match(appSource, /const sidebarCatalogMaterialsCategoriesLoadRef = useRef\(false\);/);
  assert.match(appSource, /const sidebarCatalogFittingCategoriesLoadRef = useRef\(false\);/);
  assert.match(appSource, /const \[sidebarFlyoutHoveredItemKey, setSidebarFlyoutHoveredItemKey\] = useState\(""\);/);
  assert.match(appSource, /setSidebarCatalogSubmenuKey\(""\);/);
  assert.match(appSource, /setSidebarFlyoutHoveredItemKey\(""\);/);
  assert.match(appSource, /onMouseMove=\{\(\) => \{\s*setSidebarFlyoutHoveredItemKey\(item\.key\);/);
  assert.match(appSource, /setSidebarFlyoutHoveredItemKey\(item\.key\);/);
  assert.match(appSource, /sidebarFlyout\.groupKey === "catalog"[\s\S]*sidebarCatalogSubmenuItems\.length \?/);
  assert.match(appSource, /sidebarCatalogMaterialsCategorySubmenuOpen/);
  assert.match(appSource, /sidebarCatalogFittingCategoriesSubmenuOpen/);
  assert.match(appSource, /sidebarCatalogSubmenuHasNestedItems/);
  assert.match(appSource, /const sidebarFlyoutPaneStyle = sidebarFlyout/);
  assert.match(appSource, /const sidebarFlyoutNestedPaneStyle = sidebarFlyout/);
  assert.match(appSource, /const keepSidebarCatalogMaterialsNestedOpen = \(\) =>/);
  assert.match(appSource, /const keepSidebarCatalogFittingsNestedOpen = \(\) =>/);
  assert.match(appSource, /setActiveView\("catalogMaterials"\);/);
  assert.match(appSource, /activeViewRef\.current = "catalogMaterials";/);
  assert.match(appSource, /maxHeight: `calc\(100vh - \$\{sidebarFlyout\.top \+ 24\}px\)`/);
  assert.match(appSource, /width: `\$\{width\}px`,/);
  assert.match(appSource, /listMaterialCategories\(token, false, user\?\.role !== "admin"\)/);
  assert.match(appSource, /listFittingCategories\(token, false, user\?\.role !== "admin"\)/);
  assert.match(appSource, /const isHovered = item\.key === sidebarFlyoutHoveredItemKey;/);
  assert.match(appSource, /const isRouteActive = !sidebarFlyoutHoveredItemKey && item\.active;/);
  assert.match(appSource, /className="sidebar-flyout sidebar-flyout-submenu"/);
  assert.match(appSource, /sidebar-flyout-materials-submenu/);
  assert.match(appSource, /sidebar-flyout-fittings-submenu/);
  assert.match(appSource, /sidebar-flyout-catalog-card/);
  assert.match(appSource, /sidebar-flyout-catalog-thumb/);
  assert.match(appSource, /SidebarAssetIcon/);
  assert.match(appSource, /sidebar-flyout-submenu-indicator/);
  assert.match(appSource, /sidebarFlyoutCloseTimerRef\.current = window\.setTimeout/);
  assert.match(appSource, /}, 500\);/);
  assert.match(appSource, /flyoutOpen: isDesktopSidebarCollapsed && isProcessingFlyoutOpen/);
  assert.match(appSource, /routeActive:\s*isProcessingSectionView[\s\S]*sidebarFlyoutGroupKey === "processing"/);
  assert.match(appSource, /routeActive:\s*isConnectionsNavigationView[\s\S]*sidebarFlyoutGroupKey === "connections"/);
  assert.match(appSource, /routeActive:\s*isCatalogView[\s\S]*sidebarFlyoutGroupKey === "catalog"/);

  assert.match(stylesSource, /\.sidebar-shell:hover \.sidebar-collapse-handle,/);
  assert.match(stylesSource, /opacity: 0;/);
  assert.match(stylesSource, /pointer-events: none;/);
  assert.match(stylesSource, /transform: translateX\(-100%\);/);
  assert.match(stylesSource, /transform: translateX\(0\);/);
  assert.match(stylesSource, /transition:\s*opacity 0\.18s ease,/);
  assert.match(stylesSource, /\.sidebar-flyout-submenu \{/);
  assert.match(stylesSource, /\.sidebar-flyout \{[\s\S]*border-radius: 16px;/);
  assert.match(stylesSource, /\.sidebar-flyout \{[\s\S]*scrollbar-width: thin;/);
  assert.match(stylesSource, /\.sidebar-flyout::-webkit-scrollbar,[\s\S]*\.sidebar-flyout-submenu::-webkit-scrollbar \{/);
  assert.match(stylesSource, /\.sidebar-flyout-materials-submenu \{[\s\S]*background: linear-gradient\(180deg, #111a20 0%, #0d141a 100%\);/);
  assert.match(stylesSource, /\.sidebar-flyout-materials-submenu \{[\s\S]*border-radius: 16px;/);
  assert.match(stylesSource, /\.sidebar-flyout-fittings-submenu \{[\s\S]*min-width: 220px;/);
  assert.match(stylesSource, /\.sidebar-flyout-fittings-submenu \{[\s\S]*border-radius: 16px;/);
  assert.match(stylesSource, /\.sidebar-flyout-catalog-card \{[\s\S]*grid-template-columns: 32px minmax\(0, 1fr\) auto auto;/);
  assert.match(stylesSource, /\.sidebar-flyout-catalog-thumb \{[\s\S]*border-radius: 10px;/);
  assert.match(stylesSource, /\.sidebar-flyout-catalog-thumb \{[\s\S]*height: 30px;/);
  assert.match(stylesSource, /\.sidebar-flyout-catalog-label \{[\s\S]*white-space: nowrap;/);
  assert.match(stylesSource, /\.sidebar-flyout-catalog-arrow \{/);
  assert.match(stylesSource, /\.sidebar-flyout-submenu-indicator \{/);
});
